trigger:
  - master
pool:
  vmImage: windows-2019
steps:
  - task: Docker@2
    displayName: Docker Login
    inputs:
      containerRegistry: akqahub
      command: login
  - task: PowerShell@2
    inputs:
      targetType: inline
      script: |-
        Write-Host "Start - Build and Push Docker images"
        Write-Host "Import Module"
        Import-Module ".\modules\SitecoreImageBuilder" -Force

        Write-Host "Settings"
        $installSourcePath = ".\packages"
        $registry = $env:dockerRegistryHost
        $sitecoreUsername = $env:sitecoreUsername
        $sitecorePassword = $env:sitecorePassword
        $baseTags = "sitecore-*:9.1.1*ltsc2019"

        Write-Host "Restoring packages"
        SitecoreImageBuilder\Invoke-PackageRestore `
          -Path ".\images" `
          -Destination $installSourcePath `
          -Tags $baseTags `
          -SitecoreUsername $env:sitecoreUsername `
          -SitecorePassword $env:sitecorePassword

        Write-Host "Building Docker images and push to docker registry"
        SitecoreImageBuilder\Invoke-Build `
          -Path ".\images" `
          -InstallSourcePath $installSourcePath `
          -Registry $registry `
          -Tags $baseTags `
          -PushMode "WhenChanged"

        Write-Host "End - Build and Push Docker images"
        env:
          sitecorePassword: $(sitecorePassword)
