# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: 'akqahub'
    command: 'login'
- task: PowerShell@2
  displayName: Build and Push Docker images
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Start - Build and Push Docker images"
      # Load module
      Write-Host "Import Module"
      Import-Module ".\modules\SitecoreImageBuilder" -Force
      
      Write-Host "Settings"
      # Settings
      $installSourcePath = ".\packages"
      $registry = $(dockerRegistryHost)
      $sitecoreUsername = $(sitecoreUsername)
      $sitecorePassword = $(sitecorePassword)      
      $baseTags = "sitecore-*:9.1.1*ltsc2019"
      
      # Restore packages needed for base images, only files missing in $installSourcePath will be downloaded
      Write-Host "Restoring packages"
      SitecoreImageBuilder\Invoke-PackageRestore `
          -Path ".\images" `
          -Destination $installSourcePath `
          -Tags $baseTags `
          -SitecoreUsername $sitecoreUsername `
          -SitecorePassword $sitecorePassword
      
      # Build and push base images
      Write-Host "Building Docker images and push to docker registry"
      SitecoreImageBuilder\Invoke-Build `
          -Path ".\images" `
          -InstallSourcePath $installSourcePath `
          -Registry $registry `
          -Tags $baseTags `
          -PushMode "WhenChanged"
      Write-Host "End - Build and Push Docker images"'
